### ISSUE TITLE
Persistent corpses not working?

### ISSUE THREAD

**Issue by ghost** [NebulousCloud/helix-plugins#3]
It would seem persistent corpses does not save (on reboot) or drop items on death when set to. Whenever the corpse's inventory is accessed, the following message would return multiple times:

"Someone else using this!"

No errors displayed in the console.log.

**Comment by ghost** [comment]
I have the same problem too. Haven't found a fix yet.

**Comment by Teskocf** [comment]
Same problem

**Comment by impulsh** [comment]
Corpses do not save by design. If you want items to drop, you'll need to add `ITEM.dropOnDeath = true` to any item that you want to be added to the corpse inventory.
